name: Pipeline

on:
 push:
    branches:
      - master
jobs:
    build:
        name: Azure Pipelin
        runs-on: ubuntu-latest
        steps:
        - name: AzurePipeline Action
          uses: Azure/pipelines@v1
          with:
             azure-devops-project-url: https://dev.azure.com/gauravskumar/AgileProject
             azure-pipeline-name: 'azureworkflow'
             azure-devops-token: ${{secrets.AZURE_DEVOPS_TOKEN}}
